
#ifndef MYCOMPILLER_SOURCES_H
#define MYCOMPILLER_SOURCES_H

#include <AddExpression.h>
#include <MulExpression.h>
#include <DivExpression.h>
#include <NumExpression.h>
#include <ModuloExpression.h>
#include <SubstractExpression.h>
#include <IdentExpression.h>
#include <Assignment.h>
#include <StatementList.h>
#include <grammar/Program.h>
#include <Statement.h>
#include <PrintStatement.h>
#include <ReadStatement.h>
#include <IfStatement.h>
#include <LessExpression.h>
#include <GreaterExpression.h>
#include <GreaterOrEqualExpression.h>
#include <EqualExpression.h>
#include <LessOrEqualExpression.h>
#include <Scope.h>
#include <VariableDeclaration.h>
#include <WhileStatement.h>
#include <BaseObject.h>
#include <ClassObject.h>
#include <Integer.h>
#include <BoolObject.h>
#include <CallArgumentList.h>
#include <ClassMethod.h>
#include <MethodArgumentList.h>
#include <ClassBody.h>
#include <MethodCallExpression.h>
#include <ReturnStatement.h>
#include <MethodCallStmt.h>
#include <Class.h>
#include <ClassField.h>
#include <ClassList.h>
#include <ClassMain.h>
#include <BaseType.h>
#include <IntegerType.h>
#include <VoidType.h>
#include <BoolType.h>
#include <ClassType.h>
#include <FunctionType.h>
#include <BinaryExpression.h>
#include <ThisExpression.h>
#include <NewExpression.h>

#endif //MYCOMPILLER_SOURCES_H
